# -*- coding: utf-8 -*-
"""Logical Programming.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17eP6Q0ejuZ6-n7gcQH8DCS_-MgRZKOPo
"""

speed = int(input('How many kilometers per hour are you traveling at?'))
belt = input('are you wearing a seat belt?')

if (speed > 80) or (belt != 'yes'):
  print('sorry sir,i have to give you a traffic fine.')

"""### Award.py"""

# Displaying the time taken to complete swimming

Swimming_time = int(input('Time taken to complete swimming(in minutes):'))

# Displaying the time taken to complete cycling
Cycling_time = int(input('Time taken to complete cycling(in minutes):'))

# Displaying the time taken to complete running
Runnung_time = int(input('Time taken to complete running(in minutes):'))

# Calculating Total time in completing the Triathlon

Total_time = Swimming_time + Cycling_time + Runnung_time

if Total_time <= 100:
  print('You receive Provincial colours')
elif 101<Total_time<=105:
  print('You receive Provincial half colours')
elif 106<Total_time<=110:
  print('You receive Provincial scroll')
else:
  print('No Award')